### ISSUE TITLE
Labs and In-Person Meetings

### ISSUE THREAD

**Issue by kdjohnson** [Aaron-G-9/reactjs-calendar#59]
@Aaron-G-9  To further differentiate between a lab and an regular meeting especially regarding the colouring of events. I propose to add a badge to the lab events. This would help making it clearer about why the colours of `CS 101`  have different colours in the situation of it having a lab and in-person meetings. What do you think? Which icon would you prefer?  Maybe just having text that says `Lab` or `SI`? Or we could let it how it is which I think is also a perfectly valid way to go.

**Comment by amgoodfellow** [comment]
That's a good idea - there are icons on the current production version of MySail for labs, SI, and lectures. If we can continue using those that would be nice

![image](https://user-images.githubusercontent.com/19152201/29170992-e14ee90e-7da8-11e7-8a5f-a40cf56f7130.png)

**Comment by amgoodfellow** [comment]
Closing because I was confused. Talking with KaJuan, this could be added later, but isn't really necessary
